spring:
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 30
  datasource:
    druid:
      stat-view-servlet:
        login-username: pallas
        login-password: pallas
        resetEnable: true
    dynamic:
      druid:
        initial-size: 20
        max-active: 50
        min-idle: 20
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 25200000
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        validation-query: select 1
        validation-query-timeout: 20
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat,wall
        stat:
          merge-sql: true
          log-slow-sql: false
          slow-sql-millis: 1
        wall:
          condition-and-alway-true-allow: true
          condition-and-alway-false-allow: true
          condition-double-const-allow: true
      primary: mysql
      datasource:
        mysql:
          username: root
          password: kI7ES+VBEmuAK3A30z6qr5S3vuBU1swuNI7kEwyr3saQFjeSmvzxRWp86MYctfxk/XvG04A5+KlMj0WujCzs9g==
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/pls_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useAffectedRows=true
          druid:
            initial-size: 10
            max-active: 50
            min-idle: 10
            public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJG6ewGvtRdG3jzVaVjKThI3T8q0d7dVyniZ38SlgPfu5U0jyMxBXVTUveiybUvwUfNWx2hcDglcgCAP8npuIEcCAwEAAQ==